### ISSUE TITLE
Normalize Icons in SocialLinks Component

### ISSUE THREAD

**Issue by majordwarf** [MovingBlocks/ModuleSite#23]
For Hacktoberfest - _Register at [Hacktoberfest](https://hacktoberfest.digitalocean.com) before submitting a Pull Request_

----------------
Right now the the `SocialLinks` is using icons from the `react-share` package to create sharing links for social media. Meanwhile the footer uses icons from `react-icons/fa` (Font awesome) package to link to our pages on various platforms.

It'd be better if we switch to `reac-icons/fa`'s icon sitewide to maintain uniformity and reduce the project's dependencies on multiple packages for similar use case.

**Comment by geekysrm** [comment]
@majordwarf, I would like to take up this issue! :)

**Comment by majordwarf** [comment]
Sure go ahead :smile: !

**Comment by GraceChiamaka** [comment]
@majordwarf Can I take up this issue?

**Comment by TheShubham99** [comment]
@majordwarf Is this issue resolved?

**Comment by majordwarf** [comment]
Nope, you can work on it @TheShubham99

**Comment by TheShubham99** [comment]
@majordwarf Sure.

**Comment by endurance21** [comment]
@majordwarf  can i work on this one?
